imagesize: 640
conf_thres: 0.35
max_det: 1000
iou_thres: 0.6
classes: ~
agnostic_nms: false
half: false
augment: false
device : 'cuda:0'
weights: '/media/ubuntu/data/Simweights/weights/yolov5hand_m.pth'
